// ball.town static generator.
// Reads data/cities.js and emits, for every city:
//   city/<slug>.html        (from tools/city.template.html)
//   city/<slug>.webmanifest
// and rewrites the city cards in index.html between the CITIES markers.
//
// Run:  node tools/build.mjs   (or: npm run build)
// No dependencies. Commit the generated files — GitHub Pages serves
// them as-is (it does not run this script).

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { cities } = require(join(root, "data", "cities.js"));

const template = readFileSync(join(root, "tools", "city.template.html"), "utf8");
const THEME = "#0D141D";

const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function tagline(city) {
  if (city.tagline) return city.tagline;
  return (
    "<b>Every pro team, one page.</b> Upcoming games for every " +
    esc(city.shortName) +
    " club, with dates and start times shown in your local time."
  );
}

function manifest(slug, city) {
  return {
    name: "ball.town " + city.abbr,
    short_name: "ball.town " + city.abbr,
    description: "Upcoming games for every " + city.name + " pro team.",
    start_url: slug + ".html",
    scope: "./",
    display: "standalone",
    background_color: THEME,
    theme_color: THEME,
    icons: [
      { src: "../assets/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "../assets/icons/icon-512.png", sizes: "512x512", type: "image/png" },
      { src: "../assets/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" }
    ]
  };
}

function cityPage(slug, city) {
  return template
    .replace(/\{\{SLUG\}\}/g, slug)
    .replace(/\{\{NAME\}\}/g, esc(city.name))
    .replace(/\{\{ABBR\}\}/g, esc(city.abbr || ""))
    .replace(/\{\{MANIFEST\}\}/g, slug + ".webmanifest")
    .replace(/\{\{TAGLINE\}\}/g, tagline(city))
    .replace(/\{\{STRIP_LABEL\}\}/g, esc(city.stripLabel || "Up next in " + city.shortName));
}

function indexCards() {
  return Object.entries(cities)
    .map(([slug, city]) => {
      const names = city.teams.map((t) => esc(t.short || t.name)).join(" · ");
      return (
        '  <a class="city-card" href="city/' + slug + '.html">\n' +
        "    <h2>" + esc(city.name) + "</h2>\n" +
        "    <p>" + names + "</p>\n" +
        "  </a>"
      );
    })
    .join("\n");
}

const START = "<!-- CITIES:START (generated by tools/build.mjs — do not edit by hand) -->";
const END = "<!-- CITIES:END -->";

let written = 0;
for (const [slug, city] of Object.entries(cities)) {
  writeFileSync(join(root, "city", slug + ".html"), cityPage(slug, city));
  writeFileSync(
    join(root, "city", slug + ".webmanifest"),
    JSON.stringify(manifest(slug, city), null, 2) + "\n"
  );
  written += 2;
  console.log("  city/" + slug + ".html + .webmanifest");
}

const indexPath = join(root, "index.html");
let index = readFileSync(indexPath, "utf8");
const block = START + "\n" + indexCards() + "\n  " + END;
const re = new RegExp(START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "[\\s\\S]*?" + END);
if (!re.test(index)) {
  throw new Error("index.html is missing the CITIES:START/END markers.");
}
index = index.replace(re, block);
writeFileSync(indexPath, index);

console.log(
  "Generated " + written + " files for " + Object.keys(cities).length +
  " cities, and updated index.html."
);
